# Generated by Django 5.0.3 on 2024-03-31 18:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid5, editable=False, unique=True)),
                ('url', models.URLField()),
                ('resolved_title', models.CharField()),
                ('resolved_status', models.IntegerField()),
                ('resolved_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookmarkTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, editable=False, unique=True)),
                ('bookmarks', models.ManyToManyField(to='bookmarks.bookmark')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid5, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, editable=False, unique=True)),
                ('bookmarks', models.ManyToManyField(to='bookmarks.bookmark')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
