# Generated by Django 5.0.3 on 2024-03-31 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookmark',
            table='bookmark',
        ),
        migrations.AlterModelTable(
            name='bookmarktag',
            table='bookmark_tag',
        ),
        migrations.AlterModelTable(
            name='domain',
            table='domain',
        ),
    ]
