# Generated by Django 5.0.3 on 2024-03-31 18:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_alter_bookmark_table_alter_bookmarktag_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid5, editable=False, null=True, unique=True),
        ),
    ]
