# Generated by Django 5.0.3 on 2024-03-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_alter_bookmark_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='resolved_description',
            field=models.TextField(null=True),
        ),
    ]
