# Generated by Django 5.0.3 on 2024-03-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0004_alter_bookmark_resolved_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
