# Generated by Django 5.0.3 on 2024-03-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0006_alter_bookmark_resolved_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
