# Generated by Django 5.0.4 on 2024-04-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0008_alter_bookmark_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-saved_on']},
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='created_at',
            new_name='saved_on',
        ),
    ]
